AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'API deployed with Serverless Base API'

Globals:
  Function:
    Timeout: 10

Resources:
  SampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../dist/
      Handler: index.handler
      Runtime: nodejs8.10
      Events:
        Sample:
          Type: Api
          Properties:
            Path: /hello
            Method: get

Outputs:
  SampleApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  SampleFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt SampleFunction.Arn
  SampleFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt SampleFunctionRole.Arn
